version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: default.Dockerfile
    container_name: app
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - PG_USER_NAME=pguser
      - PG_PASS=pguser
      - PG_DB=db
      - PG_SCHEMA=public
      - PG_HOST=postgres
      - PG_PORT=5432
    ports:
      - 9229:9229
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
  postgres:
    image: postgres:latest@sha256:d5787305ec0a3b9a24d0108cb5fdbb4befbd809f85639bf04aa1941138df9701
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: db
      TZ: "America/Sao_Paulo"
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
